export type DiscoverCategoryId =
  | 'all'
  // World
  | 'world-news'
  | 'ai-tech'
  | 'business-finance'
  | 'world-sports'
  | 'world-life'
  // Singapore
  | 'singapore-news'
  | 'singapore-tech'
  | 'singapore-business'
  | 'singapore-sports'
  | 'singapore-life';

export type DiscoverCategory = {
  id: DiscoverCategoryId;
  label: string;
};

export type AiSummary = {
  what:    string;
  context: string;
  impact:  string;
};

export type DiscoverStory = {
  id: string;
  category: Exclude<DiscoverCategoryId, 'all'>;
  headline: string;
  summary: string;
  whyItMatters: string;
  source: string;
  readTime: string;
  publishedAt?: string;
  imageUrl?: string;
  articleUrl?: string;
  aiSummary?: AiSummary; // pre-generated by pipeline — zero runtime API cost
};
