import type { TechRelease } from './types';

// Auto-generated by `npm run home:rss:run`. Do not edit manually.
export const techReleasesUpdatedAt = '2026-06-07T23:04:21.510Z';
export const generatedTechReleases: TechRelease[] = [
  {
    "id": "tech-1",
    "name": "Manus Shopify Connector",
    "category": "Web",
    "description": "This tool helps users build and manage their Shopify stores directly from a chat interface. Its unique feature is the seamless integration of e-commerce management with conversational support, making store management easier and more accessible.",
    "domain": "producthunt.com",
    "initials": "MS",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-07",
    "url": "https://www.producthunt.com/products/manus-shopify-connector"
  },
  {
    "id": "tech-2",
    "name": "Wave",
    "category": "Web",
    "description": "This app allows users to convert their spoken words into written text, whether they want to store it locally or in the cloud. It stands out by offering flexibility in how and where you save your transcriptions.",
    "domain": "producthunt.com",
    "initials": "W",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-07",
    "url": "https://www.producthunt.com/products/wave-16"
  },
  {
    "id": "tech-3",
    "name": "CabinLink",
    "category": "Web",
    "description": "This mobile news app provides real-time flight maps and updates for travelers using cabin Wi-Fi. It stands out by offering a visual tracking experience that keeps users informed about their journey directly from the in-flight connection.",
    "domain": "producthunt.com",
    "initials": "C",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-07",
    "url": "https://www.producthunt.com/products/cabinlink"
  },
  {
    "id": "tech-4",
    "name": "QWERTYS",
    "category": "Web",
    "description": "This web tool helps users get support for keyboard issues by connecting them with a community of problem-solvers. Its unique approach fosters collaboration, allowing users to share tips and solutions to keep keyboards functioning smoothly.",
    "domain": "producthunt.com",
    "initials": "Q",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-07",
    "url": "https://www.producthunt.com/products/qwertys"
  },
  {
    "id": "tech-5",
    "name": "Job Postings API",
    "category": "Dev Tools",
    "description": "This API helps developers access and analyze over 1.8 million job postings in the US. It stands out for providing real-time data updates and comprehensive job market insights.",
    "domain": "producthunt.com",
    "initials": "JP",
    "iconBg": "#FAEEDA",
    "releasedDate": "2026-06-07",
    "url": "https://www.producthunt.com/products/free-job-postings-api"
  },
  {
    "id": "tech-6",
    "name": "Dreambeans by Google Labs",
    "category": "AI / ML",
    "description": "This app delivers personalized daily AI news stories tailored to your interests based on your Google apps. It stands out by using your existing data to curate content that feels relevant and engaging just for you.",
    "domain": "producthunt.com",
    "initials": "DB",
    "iconBg": "#E6F1FB",
    "releasedDate": "2026-06-07",
    "url": "https://www.producthunt.com/products/google-labs"
  },
  {
    "id": "tech-7",
    "name": "MAI-Image-2.5",
    "category": "Web",
    "description": "This web tool allows users to generate and edit images with detailed control over various scenes. Its unique feature is the ability to finely manipulate aspects of the image, ensuring highly customized results.",
    "domain": "producthunt.com",
    "initials": "M",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-07",
    "url": "https://www.producthunt.com/products/mai-image-2-5"
  },
  {
    "id": "tech-8",
    "name": "Smmall Cloud for iOS",
    "category": "Mobile",
    "description": "This app allows iPad and iPhone users to easily share files with friends and colleagues. Its straightforward interface makes file sharing quick and hassle-free, setting it apart from more complex tools.",
    "domain": "producthunt.com",
    "initials": "SC",
    "iconBg": "#EAF3DE",
    "releasedDate": "2026-06-07",
    "url": "https://www.producthunt.com/products/smmall-cloud"
  }
];
