import type { NewStartup } from './types';

// Auto-generated by `npm run home:rss:run`. Do not edit manually.
export const newStartupsUpdatedAt = '2026-06-08T23:00:05.121Z';
export const generatedNewStartups: NewStartup[] = [
  {
    "id": "startup-1",
    "avatarColor": "#378ADD",
    "name": "Microsoft AI chief says company was “set",
    "domain": "microsoftaichiefsayscompanywasset.com",
    "initials": "MA",
    "stage": "Seed",
    "sector": "AI",
    "description": "Microsoft AI develops tools and features to enhance various applications using artificial intelligence for businesses and consumers. Their substantial investment in OpenAI, totaling over $13 billion, highlights their commitment to leading the AI sector.",
    "raisedAmount": "$13B",
    "foundedYear": 2026,
    "url": "https://venturebeat.com/technology/microsoft-ai-chief-says-company-was-set-free-from-openai-to-pursue-superintelligence"
  },
  {
    "id": "startup-2",
    "avatarColor": "#1D9E75",
    "name": "Supabase doubles valuation to $10B in 8 ",
    "domain": "supabasedoublesvaluationto10bin8.com",
    "initials": "SD",
    "stage": "Seed",
    "sector": "AI",
    "description": "Supabase builds open-source tools for developers looking to streamline their database needs. Recently, it doubled its valuation to $10 billion and secured $10 billion in seed funding, making it a significant player in the tech sector.",
    "raisedAmount": "$10B",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/05/supabase-doubles-valuation-to-10b-in-8-months/"
  },
  {
    "id": "startup-3",
    "avatarColor": "#7F77DD",
    "name": "Helion, the Sam Altman-backed fusion sta",
    "domain": "helionthesamaltmanbackedfusionsta.com",
    "initials": "HT",
    "stage": "Seed",
    "sector": "Tech",
    "description": "Helion builds advanced fusion technology aimed at providing clean energy solutions for tech companies like Microsoft. With $465 million in seed funding, they are well-positioned to complete a power plant by 2028, making them a key player in the clean energy sector.",
    "raisedAmount": "$465M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/04/helion-the-sam-altman-backed-fusion-startup-raises-465m-to-build-a-power-plant-for-microsoft/"
  },
  {
    "id": "startup-4",
    "avatarColor": "#DD7767",
    "name": "Quick-commerce FirstClub doubles valuati",
    "domain": "quickcommercefirstclubdoublesvaluati.com",
    "initials": "QF",
    "stage": "Seed",
    "sector": "Tech",
    "description": "FirstClub is a mobile news app that connects users with instant updates on local events and trends. The Bengaluru-based startup has quickly achieved over 1 million orders and boasts a $50 million annualized GMV run rate in just one year since its launch, making it a notable player in the quick-commerce space.",
    "raisedAmount": "$255M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/03/firstclub-doubles-valuation-to-255m-in-nine-months-on-quality-first-grocery-bet/"
  },
  {
    "id": "startup-5",
    "avatarColor": "#3DAD6B",
    "name": "Coralogix",
    "domain": "coralogix.com",
    "initials": "C",
    "stage": "Seed",
    "sector": "AI",
    "description": "Coralogix builds AI-driven monitoring tools for infrastructure that help businesses track and troubleshoot their systems in real-time. With a significant $200 million in seed funding, they are positioned to become key players in supporting the growing AI landscape.",
    "raisedAmount": "$200M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/03/coralogix-raises-200m-in-race-to-build-the-monitoring-layer-for-ai-agents/"
  },
  {
    "id": "startup-6",
    "avatarColor": "#C0852A",
    "name": "Cyera eyes $12B valuation at 80x ARR mul",
    "domain": "cyeraeyes12bvaluationat80xarrmul.com",
    "initials": "CE",
    "stage": "Seed",
    "sector": "Tech",
    "description": "Cyera builds a cybersecurity mobile news app that helps businesses protect their sensitive data. The company is gaining attention after raising $12 billion in seed funding and approaching a $12 billion valuation, making it a significant player to monitor in the tech space.",
    "raisedAmount": "$12B",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/02/cyera-eyes-12b-valuation-at-80x-arr-multiple-despite-operating-losses/"
  }
];
