// Auto-generated by `npm run home:rss:run`. Do not edit manually.
export const startupOfDayUpdatedAt = '2026-06-07T23:04:21.510Z';
export const generatedStartupOfDay = {
  "id": "startup-of-day",
  "name": "Microsoft AI",
  "oneLiner": "Microsoft builds AI tools to transform business operations.",
  "foundedYear": "2023",
  "problemSolved": "Microsoft AI develops advanced artificial intelligence tools tailored for businesses. The startup addresses the challenge of integrating AI into everyday business processes efficiently. Their significant partnership with OpenAI and a massive seed funding of $13 billion positions them as a leading innovator in AI technology.",
  "imageUrl": "https://picsum.photos/seed/Microsoft%20AI/1400/900",
  "storyTitle": "Startup of the Day: Microsoft AI",
  "storyParagraphs": [
    "Founded in 2023, Microsoft AI emerged as part of Microsoft’s broader strategy to enhance its technology through artificial intelligence. Driven by the company’s AI chief, the initiative received immediate attention and backing, securing a remarkable $13 billion in seed funding to kickstart its ambitious plans.",
    "Microsoft AI focuses on creating user-friendly AI tools designed specifically for businesses. By streamlining the integration of AI into workflows, they help companies harness the power of machine learning and data analytics. Their ongoing collaboration with OpenAI also enhances the quality and capabilities of their offerings.",
    "The AI landscape is rapidly evolving, making this the perfect time for Microsoft AI's entry. With increasing demand for efficient and intelligent technology solutions, their robust funding allows them to innovate quickly and remain at the forefront of the industry. Businesses now more than ever need tools to navigate complexities, and Microsoft AI is poised to deliver."
  ]
} as const;
