import type { NewStartup } from './types';

// Auto-generated by `npm run home:rss:run`. Do not edit manually.
export const newStartupsUpdatedAt = '2026-06-07T23:04:21.510Z';
export const generatedNewStartups: NewStartup[] = [
  {
    "id": "startup-1",
    "avatarColor": "#378ADD",
    "name": "Microsoft AI chief says company was “set",
    "domain": "microsoftaichiefsayscompanywasset.com",
    "initials": "MA",
    "stage": "Seed",
    "sector": "AI",
    "description": "Microsoft AI chief leads efforts to enhance technology with a strong focus on artificial intelligence tools for businesses. The company's ongoing partnership with OpenAI and substantial funding of $13 billion make it a key player in the AI landscape.",
    "raisedAmount": "$13B",
    "foundedYear": 2026,
    "url": "https://venturebeat.com/technology/microsoft-ai-chief-says-company-was-set-free-from-openai-to-pursue-superintelligence"
  },
  {
    "id": "startup-2",
    "avatarColor": "#1D9E75",
    "name": "Supabase doubles valuation to $10B in 8 ",
    "domain": "supabasedoublesvaluationto10bin8.com",
    "initials": "SD",
    "stage": "Seed",
    "sector": "AI",
    "description": "Supabase builds an open-source platform for developers to create and manage databases easily. The company recently doubled its valuation to $10 billion, highlighting its rapid growth and strong market demand.",
    "raisedAmount": "$10B",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/05/supabase-doubles-valuation-to-10b-in-8-months/"
  },
  {
    "id": "startup-3",
    "avatarColor": "#7F77DD",
    "name": "Helion, the Sam Altman-backed fusion sta",
    "domain": "helionthesamaltmanbackedfusionsta.com",
    "initials": "HT",
    "stage": "Seed",
    "sector": "Tech",
    "description": "Helion builds fusion energy technology aimed at powering companies like Microsoft. With $465M in seed funding, they are on track to complete a significant power plant by 2028.",
    "raisedAmount": "$465M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/04/helion-the-sam-altman-backed-fusion-startup-raises-465m-to-build-a-power-plant-for-microsoft/"
  },
  {
    "id": "startup-4",
    "avatarColor": "#DD7767",
    "name": "Quick-commerce FirstClub doubles valuati",
    "domain": "quickcommercefirstclubdoublesvaluati.com",
    "initials": "QF",
    "stage": "Seed",
    "sector": "Tech",
    "description": "FirstClub is a mobile news app that serves quick-commerce enthusiasts by providing real-time updates and insights. The Bengaluru startup has impressively crossed 1 million orders and achieved a $50 million annualized GMV run rate within just a year since its launch.",
    "raisedAmount": "$255M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/03/firstclub-doubles-valuation-to-255m-in-nine-months-on-quality-first-grocery-bet/"
  },
  {
    "id": "startup-5",
    "avatarColor": "#3DAD6B",
    "name": "Coralogix",
    "domain": "coralogix.com",
    "initials": "C",
    "stage": "Seed",
    "sector": "AI",
    "description": "Coralogix builds monitoring tools for AI systems to help businesses manage and troubleshoot their infrastructure. The startup recently raised $200 million in seed funding, highlighting a strong investor interest in the growing need for AI performance management.",
    "raisedAmount": "$200M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/03/coralogix-raises-200m-in-race-to-build-the-monitoring-layer-for-ai-agents/"
  },
  {
    "id": "startup-6",
    "avatarColor": "#C0852A",
    "name": "Cyera eyes $12B valuation at 80x ARR mul",
    "domain": "cyeraeyes12bvaluationat80xarrmul.com",
    "initials": "CE",
    "stage": "Seed",
    "sector": "Tech",
    "description": "Cyera builds a cybersecurity platform that helps businesses protect their data in real time. The company is making headlines as it approaches a $12 billion valuation after securing a $12 billion seed round.",
    "raisedAmount": "$12B",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/06/02/cyera-eyes-12b-valuation-at-80x-arr-multiple-despite-operating-losses/"
  }
];
