import type { TechRelease } from './types';

// Auto-generated by `npm run home:rss:run`. Do not edit manually.
export const techReleasesUpdatedAt = '2026-06-08T23:00:05.121Z';
export const generatedTechReleases: TechRelease[] = [
  {
    "id": "tech-1",
    "name": "Honen",
    "category": "Web",
    "description": "Automated teaching and learning infrastructure helps companies streamline their training processes and enhance employee development. It stands out for its adaptability, allowing organizations of any size to customize the learning experience for their unique needs.",
    "domain": "producthunt.com",
    "initials": "H",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-08",
    "url": "https://www.producthunt.com/products/honen"
  },
  {
    "id": "tech-2",
    "name": "Sigma File Manager",
    "category": "Web",
    "description": "This file manager app helps users organize, access, and manage their files across multiple platforms. Its open-source nature and modern design set it apart, making it a flexible choice for anyone looking to streamline their file management.",
    "domain": "producthunt.com",
    "initials": "SF",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-08",
    "url": "https://www.producthunt.com/products/sigma-file-manager"
  },
  {
    "id": "tech-3",
    "name": "NTSC-RS",
    "category": "Web",
    "description": "This app allows users to emulate the look of analog TV and VHS tapes for video projects. It stands out for its open-source nature, enabling customization and collaboration within the community.",
    "domain": "producthunt.com",
    "initials": "N",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-08",
    "url": "https://www.producthunt.com/products/ntsc-rs"
  },
  {
    "id": "tech-4",
    "name": "Claude Artifact Player",
    "category": "AI / ML",
    "description": "This app allows users to run their Claude AI artifacts directly on their devices without relying on a browser or cloud services. It offers a streamlined, offline experience that enhances performance and privacy.",
    "domain": "producthunt.com",
    "initials": "CA",
    "iconBg": "#E6F1FB",
    "releasedDate": "2026-06-08",
    "url": "https://www.producthunt.com/products/claude-artifact-player"
  },
  {
    "id": "tech-5",
    "name": "Tamadoggo",
    "category": "AI / ML",
    "description": "This app helps pet owners track their furry friends' daily activities and milestones, providing a personalized journal for each pet. Its unique AI insights offer tailored recommendations to improve your pet's well-being and enrich their life experiences.",
    "domain": "producthunt.com",
    "initials": "T",
    "iconBg": "#E6F1FB",
    "releasedDate": "2026-06-08",
    "url": "https://www.producthunt.com/products/tamadoggo"
  },
  {
    "id": "tech-6",
    "name": "The Virtual OS Museum",
    "category": "Web",
    "description": "Experience vintage operating systems directly on your desktop with this interactive web app designed for tech enthusiasts and nostalgia lovers. It stands out by offering an authentic look and feel of classic software, allowing you to explore computing history with ease.",
    "domain": "producthunt.com",
    "initials": "TV",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-08",
    "url": "https://www.producthunt.com/products/the-virtual-os-museum"
  },
  {
    "id": "tech-7",
    "name": "Supaste",
    "category": "Web",
    "description": "This clipboard manager streamlines text and image copying for Mac users, helping them organize and retrieve their copied items effortlessly. What sets it apart is its intuitive interface and powerful search functionality that allows quick access to previous clippings.",
    "domain": "producthunt.com",
    "initials": "S",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-06-08",
    "url": "https://www.producthunt.com/products/supaste"
  },
  {
    "id": "tech-8",
    "name": "Vaani",
    "category": "AI / ML",
    "description": "This app enables creators, brands, and studios to easily create lip-synced AI dubbing for their videos. Its standout feature is the seamless integration of advanced AI technology that adapts speech patterns to match the original video, making it look natural and authentic.",
    "domain": "producthunt.com",
    "initials": "V",
    "iconBg": "#E6F1FB",
    "releasedDate": "2026-06-08",
    "url": "https://www.producthunt.com/products/vaani-2"
  }
];
