import type { NewStartup } from './types';

// Auto-generated by `npm run home:rss:run`. Do not edit manually.
export const newStartupsUpdatedAt = '2026-05-31T23:10:00.390Z';
export const generatedNewStartups: NewStartup[] = [
  {
    "id": "startup-1",
    "avatarColor": "#378ADD",
    "name": "After Nvidia’s $20B not-acqui-hire, AI c",
    "domain": "afternvidias20bnotacquihireaic.com",
    "initials": "AN",
    "stage": "Seed",
    "sector": "AI",
    "description": "Groq is a chipmaker transitioning from hardware to AI inference, aiming to enhance how AI models respond to inputs. The company recently raised $20B in funding, signaling strong investor confidence in their shift towards AI innovation.",
    "raisedAmount": "$20B",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/05/29/after-nvidias-20b-not-acqui-hire-ai-chip-startup-groq-reportedly-raising-650m/"
  },
  {
    "id": "startup-2",
    "avatarColor": "#1D9E75",
    "name": "This chip startup just raised $135M on a",
    "domain": "thischipstartupjustraised135mona.com",
    "initials": "TC",
    "stage": "Seed",
    "sector": "AI",
    "description": "XCENA develops advanced memory chips aimed at enhancing AI performance for tech companies. The startup attracted significant attention after raising $135 million in seed funding, positioning itself as a key player in the evolving AI landscape.",
    "raisedAmount": "$135M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/05/29/xcena-secures-135m-at-570m-valuation-betting-on-memory-as-ais-real-bottleneck/"
  },
  {
    "id": "startup-3",
    "avatarColor": "#7F77DD",
    "name": "Glean’s top line crosses $300M as AI bud",
    "domain": "gleanstoplinecrosses300masaibud.com",
    "initials": "GT",
    "stage": "Seed",
    "sector": "AI",
    "description": "Glean builds an AI-powered search tool for enterprises, helping organizations find and use their internal information more effectively. The startup recently tripled its annual revenue to over $300 million, making it a notable competitor in a space crowded with tech giants.",
    "raisedAmount": "$300M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/05/28/gleans-top-line-crosses-300m-as-ai-budget-cutting-becomes-its-major-selling-point/"
  },
  {
    "id": "startup-4",
    "avatarColor": "#DD7767",
    "name": "H1",
    "domain": "h1.com",
    "initials": "H",
    "stage": "Seed",
    "sector": "AI",
    "description": "H1 is a mobile news app that provides healthcare professionals with access to unique data about doctors and their specialties. The startup raised $40 million in seed funding, highlighting strong investor interest in its innovative approach to combining AI and medical information.",
    "raisedAmount": "$40M",
    "foundedYear": 2026,
    "url": "https://techcrunch.com/2026/05/28/h1-secures-40m-from-cvs-proving-saas-startups-can-still-attract-investment/"
  }
];
