import type { TechRelease } from './types';

// Auto-generated by `npm run home:rss:run`. Do not edit manually.
export const techReleasesUpdatedAt = '2026-05-31T23:10:00.390Z';
export const generatedTechReleases: TechRelease[] = [
  {
    "id": "tech-1",
    "name": "Clipto",
    "category": "Web",
    "description": "This app allows users to search through vast amounts of media using natural language, making it easy for anyone to find specific content. Its fully local approach ensures that users can access their desired information quickly and without relying on external servers.",
    "domain": "producthunt.com",
    "initials": "C",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-05-31",
    "url": "https://www.producthunt.com/products/clipto-ai"
  },
  {
    "id": "tech-2",
    "name": "Wingbits AI",
    "category": "AI / ML",
    "description": "This app provides real-time monitoring and alerts for aircraft, specifically designed for pilots and aviation professionals. Its AI-driven technology offers predictive insights that enhance safety and decision-making during flights.",
    "domain": "producthunt.com",
    "initials": "WA",
    "iconBg": "#E6F1FB",
    "releasedDate": "2026-05-31",
    "url": "https://www.producthunt.com/products/wingbits-ai"
  },
  {
    "id": "tech-3",
    "name": "Openstatus MCP Health Checker",
    "category": "AI / ML",
    "description": "Test your MCP servers as if you're using an actual AI client with this health checker tool. It stands out by providing a more realistic assessment instead of just a basic ping test.",
    "domain": "producthunt.com",
    "initials": "OM",
    "iconBg": "#E6F1FB",
    "releasedDate": "2026-05-31",
    "url": "https://www.producthunt.com/products/openstatus-2"
  },
  {
    "id": "tech-4",
    "name": "Second Brain for AI",
    "category": "AI / ML",
    "description": "This mobile news app helps users enhance their productivity by allowing them to store and manage information seamlessly across AI platforms like Claude, ChatGPT, and Cursor. Its standout feature is the persistent memory that simplifies information retrieval, making it easier to track and revisit important insights.",
    "domain": "producthunt.com",
    "initials": "SB",
    "iconBg": "#E6F1FB",
    "releasedDate": "2026-05-31",
    "url": "https://www.producthunt.com/products/second-brain-cloudflare"
  },
  {
    "id": "tech-5",
    "name": "TabTasker",
    "category": "Security",
    "description": "This mobile news app caters to users who value security and privacy while staying informed. It stands out by offering a server-free experience, ensuring that your personal data remains completely private.",
    "domain": "producthunt.com",
    "initials": "T",
    "iconBg": "#EEEDFE",
    "releasedDate": "2026-05-31",
    "url": "https://www.producthunt.com/products/tabtasker"
  },
  {
    "id": "tech-6",
    "name": "Web Clipper for NotebookLM",
    "category": "Web",
    "description": "This Chrome extension allows NotebookLM users to easily save and organize web content for their notes. It stands out by integrating seamlessly with NotebookLM, making the process of curating information quick and intuitive.",
    "domain": "producthunt.com",
    "initials": "WC",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-05-31",
    "url": "https://www.producthunt.com/products/web-clipper-for-notebooklm"
  },
  {
    "id": "tech-7",
    "name": "Marqly 5.0",
    "category": "AI / ML",
    "description": "This AI-powered bookmark manager helps users organize and manage their online links efficiently. Its intelligent tagging system automatically categorizes bookmarks, making it easy to find what you need without hassle.",
    "domain": "producthunt.com",
    "initials": "M5",
    "iconBg": "#E6F1FB",
    "releasedDate": "2026-05-31",
    "url": "https://www.producthunt.com/products/marqly"
  },
  {
    "id": "tech-8",
    "name": "Exstats",
    "category": "Web",
    "description": "This app helps web users keep track of their browser extensions and competitors all in one convenient place. It stands out by offering a simple and organized way to manage your extensions while providing insights into what others are using.",
    "domain": "producthunt.com",
    "initials": "E",
    "iconBg": "#E1F5EE",
    "releasedDate": "2026-05-31",
    "url": "https://www.producthunt.com/products/exstats"
  }
];
